# Generated by Django 3.2.15 on 2022-09-28 03:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myimages', '0002_itens'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Itens',
            new_name='Item',
        ),
    ]
