# Generated by Django 3.2.15 on 2022-09-28 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myimages', '0004_imagem_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagem',
            old_name='user_id',
            new_name='user',
        ),
    ]
