# Generated by Django 3.2.15 on 2022-09-28 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myimages', '0005_rename_user_id_imagem_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
