# Generated by Django 3.2.15 on 2022-09-28 19:13

from django.db import migrations, models
import myimages.models


class Migration(migrations.Migration):

    dependencies = [
        ('myimages', '0006_delete_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='foto',
            field=models.ImageField(upload_to=myimages.models.upload_to),
        ),
    ]
